name: RAG ISO27001 Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-rag-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install langchain openai chromadb datasets numpy langchain-community

      - name: Run RAG Project Script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
           pip install nbconvert jupyter
           jupyter nbconvert --to notebook --execute rag_iso27001_colab.ipynb --output output.ipynb 
        